### ISSUE TITLE
Query works without but fails with graphql-jit throwing RangeError

### ISSUE THREAD

**Issue by NexZhu** [zalando-incubator/graphql-jit#175]
Hi, I have a GraphQL API auto generated from Prisma schema using typegraphql-prisma. The following query for example working as expected with Yoga as the GraphQL server:

```graphql
query GetNodes($where: NodeWhereInput) {
    nodes(where: $where) {
        id
    }
}
```

Variables:
```json
{
  "where": {
    "ownerId": {
      "equals": 1
    }
  }
}
```

Result:
```json
{
  "data": {
    "nodes": [
      {
        "id": "6820393e-3117-460b-b22a-443dabd5a5d0"
      },
      {
        "id": "d5f7639b-5280-409d-9139-12813bc035f7"
      }
    ]
  }
}
```

But when I enable `graphql-jit`, I got this error from the same query:
```
{
  errors: [
    RangeError: Maximum call stack size exceeded
        at generateInput (/root/dev/baas/web/backend/node_modules/.pnpm/graphql-jit@0.7.4_graphql@15.8.0/node_modules/graphql-jit/src/variables.ts:153:5)
        at generateInput (/root/dev/baas/web/backend/node_modules/.pnpm/graphql-jit@0.7.4_graphql@15.8.0/node_modules/graphql-jit/src/variables.ts:332:13)
        at generateInput (/root/dev/baas/web/backend/node_modules/.pnpm/graphql-jit@0.7.4_graphql@15.8.0/node_modules/graphql-jit/src/variables.ts:376:11)
        at generateInput (/root/dev/baas/web/backend/node_modules/.pnpm/graphql-jit@0.7.4_graphql@15.8.0/node_modules/graphql-jit/src/variables.ts:332:13)
        at generateInput (/root/dev/baas/web/backend/node_modules/.pnpm/graphql-jit@0.7.4_graphql@15.8.0/node_modules/graphql-jit/src/variables.ts:376:11)
        at generateInput (/root/dev/baas/web/backend/node_modules/.pnpm/graphql-jit@0.7.4_graphql@15.8.0/node_modules/graphql-jit/src/variables.ts:332:13)
        at generateInput (/root/dev/baas/web/backend/node_modules/.pnpm/graphql-jit@0.7.4_graphql@15.8.0/node_modules/graphql-jit/src/variables.ts:376:11)
        at generateInput (/root/dev/baas/web/backend/node_modules/.pnpm/graphql-jit@0.7.4_graphql@15.8.0/node_modules/graphql-jit/src/variables.ts:332:13)
        at generateInput (/root/dev/baas/web/backend/node_modules/.pnpm/graphql-jit@0.7.4_graphql@15.8.0/node_modules/graphql-jit/src/variables.ts:376:11)
        at generateInput (/root/dev/baas/web/backend/node_modules/.pnpm/graphql-jit@0.7.4_graphql@15.8.0/node_modules/graphql-jit/src/variables.ts:332:13)
  ]
}
```

It works fine in both cases without the query parameters though:
```graphql
query GetNodes {
    nodes {
        region
    }
}
```

**Comment by boopathi** [comment]
It is probably because of circular references in the Input type definitions. Related to https://github.com/zalando-incubator/graphql-jit/issues/81 .
