### ISSUE TITLE
cjs export broken

### ISSUE THREAD

**Issue by mcollina** [zalando-incubator/graphql-jit#241]
```
Error: Package subpath './dist/error' is not defined by "exports" in /home/runner/work/mercurius/mercurius/node_modules/graphql-jit/package.json
    at exportsNotFound (node:internal/modules/esm/resolve:303:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:650:9)
    at resolveExports (node:internal/modules/cjs/loader:591:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:668:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1130:27)
    at Function.Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/home/runner/work/mercurius/mercurius/test/cache.js:7:[26](https://github.com/mercurius-js/mercurius/actions/runs/8331381446/job/22798162065?pr=1089#step:5:27))
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module.replacementCompile (/home/runner/work/mercurius/mercurius/node_modules/append-transform/index.js:60:13)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.<anonymous> (/home/runner/work/mercurius/mercurius/node_modules/append-transform/index.js:64:4)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:[28](https://github.com/mercurius-js/mercurius/actions/runs/8331381446/job/22798162065?pr=1089#step:5:29):49
```

**Comment by boopathi** [comment]
Must be the effort to support both esm and cjs - 

https://github.com/zalando-incubator/graphql-jit/commit/eac7fe3b23de264b1be723af9f1de06e3ca0ed59#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R13-R16
